# Config file for training capsules

trainer:
  file: trainer_nocs
  type: "TrainerNOCS"
  max_epochs: 60
  regularizer: 
    layer: "kernel_regularizer"
    type: "L1"
    weight: 0.1
  optimizer: 
    type: Adam
    args:
      lr: 6e-4
  scheduler:
    steps: [10, 20, 25]  
    decay_rate: 1e-1
  monitor:
    metric: "val_l2_loss"
  seed: 1234

features:
  rotation:
    use: true
  partiality:
    use: true
  translate:
    use: true

model:
  file: "tfn_capsules_multi_frame_scale_translation"
  type: "TFN_all"
  args:
    num_classes: 1024
    num_frames: 5
    num_capsules: 10

loss:
  l2_loss: 2.0
  eq_loss: 1.0
  loc_loss: 0.3
  caps_chamf_loss: 0.2
  orth_loss: 1.0
  caps_partiality_loss: 0.3
  directional_loss_partial: 0.2
  capsule_position_loss: 0.1
  caps_spatial_loss: 0.3
  inv_partiality_loss: 1.0
  chamfer_loss: 1.0
  hausdorff_loss: 0.0
  loss_shape_svd: 0.4
  separation_loss_basis: 0.8
  translation_loss_full: 0.0
  translation_loss_partial: 1.0


dataset:
  path: "/gpfs/scratch/rsajnani/rsajnani/research/test_adrien/EquiNet/NOCS-dataset-generator/src/"
  batch_size: 12
  shuffle: True
  num_points: 1024
  val_list: [val_02691156.h5]
  train_list: [train_02691156.h5]
  test_list: [val_02691156.h5]

save:
  path: "./checkpoints"
utils:
  eps: 1e-8
